feat: Requests and Events
Twasi/websocket-obs-java pull request #37
Opened 2021-05-19 14:13 UTC by ChristopheCVB

Upgraded Gson dependency to latest version
A bit of Cleanup
Added some Requests and Events

2021-05-20 06:29 UTC, TinaTiel commented
Thanks! Taking a look...

2021-05-20 06:57 UTC, TinaTiel reviewed
I've reviewed the files and will try testing locally next...Only request so far was some more javadocs on one place, otherwise looks fantastic so far!

2021-05-20 06:57 UTC, TinaTiel commented on src/main/java/net/twasi/obsremotejava/objects/Scene.java
> +    public List<Source> getAllSources() {
Could you add javadocs here explaining the difference between these two methods? 
Or rename it to something like "getSourcesIncludingGroupChildren"?

2021-05-20 06:57 UTC, TinaTiel commented on src/main/java/net/twasi/obsremotejava/OBSCommunicator.java
> +    private Gson gson;
Awesome! Closes #27

2021-05-20 07:00 UTC, TinaTiel commented on src/main/java/net/twasi/obsremotejava/OBSRemoteController.java
> +    public void registerPreviewSceneChangesCallback(Callback<PreviewSceneChangedResponse> onPreviewSceneChanged) {
Could you add this to ObsRemoteControllerUnsecuredIT#test?

2021-05-20 07:32 UTC, TinaTiel requested changes
A bit more review, requesting some changes on one thing so far. 
Otherwise testing was good, and I'll post a message to the original maintainers asking for their final feedback / if we can merge after the requested changes.

2021-05-20 07:32 UTC, TinaTiel commented on src/main/java/net/twasi/obsremotejava/OBSRemoteController.java
> +    public void playPauseMedia(String sourceName, Boolean playPause, Callback<PlayPauseMediaResponse> callback) {
Getting an "invalid request type" message when using this, can you repro?

onMessage: {
    "error": "invalid request type",
    "message-id": "4",
    "status": "error"
}

2021-05-20 10:57 UTC, TinaTiel commented on src/main/java/net/twasi/obsremotejava/OBSRemoteController.java
> +        communicator.playPauseMedia(sourceName, true, callback);
should be false

2021-05-20 10:57 UTC, TinaTiel commented on src/main/java/net/twasi/obsremotejava/OBSRemoteController.java
> +        communicator.playPauseMedia(sourceName, false, callback);
should be true

2021-05-20 11:00 UTC, ChristopheCVB commented on src/main/java/net/twasi/obsremotejava/OBSRemoteController.java
> +        communicator.playPauseMedia(sourceName, true, callback);
Nice catch, sorry ;)

2021-05-20 11:09 UTC, TinaTiel commented on src/main/java/net/twasi/obsremotejava/OBSRemoteController.java
> +    public void registerPreviewSceneChangesCallback(Callback<PreviewSceneChangedResponse> onPreviewSceneChanged) {
Tested and confirmed!

2021-05-20 17:13 UTC, TinaTiel approved these changes
Looks great! I approve!
Still pending response from owners, I'll ping them and if there's no response in a few days then merge if that's fine with you.

2021-05-20 19:28 UTC, LarsBaertschi approved these changes
Thanks for this awesome extension! Looks good to me, we'll make sure to get this released once it's merged as new minor version!

2021-05-20 19:36 UTC, ChristopheCVB commented
> Thanks for this awesome extension! Looks good to me, we'll make sure to get this released once it's merged as new minor version!

Thanks for the kind words.
Fine by me ;)

2021-05-21 10:35 UTC, ChristopheCVB commented
I'm sorry guys, there were things that bothered me. I went ahead and refactored a bit.
No change to the public API as long as developers use lambdas.

2021-05-21 10:51 UTC, ChristopheCVB commented on build.gradle
> -    jcenter()
jcenter is deprecated

2021-05-21 16:06 UTC, TinaTiel commented
Ran the tests again, all seems well.

2021-05-21 16:07 UTC, ChristopheCVB commented
> Ran the tests again, all seems well.

I added some too and ran them locally before pushing each commit, including the OBSRemoteControllerUnsecuredIT

2021-05-21 16:10 UTC, merged